# Generated by Django 4.1.4 on 2022-12-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ytsync", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videolisting",
            old_name="video_id",
            new_name="videoId",
        ),
        migrations.AddField(
            model_name="videolisting",
            name="channelTitle",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
