# Generated by Django 4.1.4 on 2022-12-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytsync', '0002_rename_video_id_videolisting_videoid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200, null=True)),
                ('key', models.TextField()),
                ('exhausted', models.BooleanField(default=False)),
            ],
        ),
    ]
