# Generated by Django 4.1.4 on 2022-12-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytsync', '0003_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolisting',
            name='description',
            field=models.TextField(),
        ),
    ]
